### ISSUE TITLE
Segmentation with the destructor of Mapper Class

### ISSUE THREAD

**Issue by mahajanparth** [NVlabs/nvblox_torch#1]
Hello , 
I have followed the steps given in the readme to install the nvblox_torch . 
But While running the nvblox_torch examples get_sdf.py i am facing issues with segmentation fault while the mapper object is being destroyed .
i have added a cygdb debug where command results screen shot : 

![get_sdf_error](https://github.com/NVlabs/nvblox_torch/assets/32522286/68d5c832-c9e3-42ed-95ac-440217a15cae)
Can somebody help me identify what could be the possible solution to mitigate it ?

**Comment by balakumar-s** [comment]
The new release should fix this issue. Can you try and confirm?

**Comment by mahajanparth** [comment]
Seems to be working wonderfully !!!
