### ISSUE TITLE
nvblox_torch installation fails

### ISSUE THREAD

**Issue by sjauhri** [NVlabs/nvblox_torch#6]
How are you using nvblox_torch (docker/native/conda/?): **conda**, **PRECXX11_ABI**

Issue Details:
When installing nvblox_torch (after successfully installing nvblox with PRECXX11_ABI), I get the following Cmake error when running the install `sh install.sh $(python -c 'import torch.utils; print(torch.utils.cmake_prefix_path)')`:

**CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBNVTOOLSEXT
    linked by target "py_nvblox" in directory /home/sjauhri/IAS_WS/isaac/ov/pkg/nvblox_torch/src/nvblox_torch/cpp**

Seems like it can't link to libnvToolsExt? It does correctly find CUDA because it first outputs: 
`-- Caffe2: CUDA detected: 11.8
-- Caffe2: CUDA nvcc is: /home/sjauhri/miniconda3/envs/isaac-sim-2023-try/bin/nvcc
-- Caffe2: CUDA toolkit directory: /home/sjauhri/miniconda3/envs/isaac-sim-2023-try
-- Caffe2: Header version is: 11.8
-- /home/sjauhri/miniconda3/envs/isaac-sim-2023-try/lib/libnvrtc.so shorthash is c993a6f1
-- USE_CUDNN is set to 0. Compiling without cuDNN support
-- Autodetected CUDA architecture(s):  8.6
-- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86`

Also, libnvtoolsext.so exists in my conda env path at /lib//libnvToolsExt.so

**Comment by balakumar-s** [comment]
Is the path for `libnvToolsExt.so` in `$LD_LIBRARY_PATH` ?

**Comment by sjauhri** [comment]
Thanks for the hint. Modifying the LD_LIBRARY_PATH did not change anything but changing PATH did. Fixed this issue by explicitly adding the 'lib' directory where libnvToolsExt.so exists to PATH:
`export PATH=/home/sjauhri/miniconda3/envs/isaac-sim-2023-new/lib:$PATH`
